### ISSUE TITLE
General - Set Up Production Database

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#204]
**Background:**
In order for our deployed application to be populated with data, we need to have a non-development database. AWS is the cloud computing provider that we previously decided on, so we'll be setting up a free-tier AWS RDS PostgreSQL database.

**Note:** This ticket must be done with project admin support for account creation and setup guidance.

---

**Steps:**
- [x] Create AWS organization account and configure user permissions
- [x] Create and configure AWS RDS PostgreSQL database within free tier
- [x] Add the secret key and URL to the production secrets on Netlify
- [ ] #344
- [ ] #343
- [x] #345
- [x] #346
- [ ] Perform tests to verify production database is working properly

**Comment by jamescd18** [comment]
AWS RDS PostgreSQL database set up and the database string has been added to the env variables in Netlify. Here are some additional action items

- [ ] Set up proper back-end ENV imports instead of using the react app way
- [ ] set up users and permissions on the production database
- [ ] load test data into the production database
- [ ] #212 
- [ ] #213 
- [ ] #214
