### ISSUE TITLE
Projects - Project Edit Form

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#361]
## Description
A new component needs to be created so that project managers can edit a project. This component will be a form that will look similar to the project details page, except that all the fields within within the project will be editable text boxes rather than view-only details about the project.

## Background
The idea is that when project managers click on the "edit" button (which will be completed in another ticket), this form will be populated with the current information of the project, so that project managers can directly edit and save the details. This ticket is to make the form that the project managers will see when they click the "edit" button. Do not worry about populating the text boxes with the current values, as that will be completed in another ticket. The focus of this ticket is to only create the front-end visual.

## Proposed Solution 
\*\***For all sections listed below, the headers for each section (Work Package Details, Dependencies, etc.) should not be editable**\*\*

### Project Details
- [x] The labels for each field will remain exactly the same and in the same location. Only the details portion for each field will change and will become input text boxes.
- [x] The "Start Date", "End Date", and "Duration" fields should become read-only input fields. They are calculated through work packages, so should not be editable. 
- [x] The links for "Slide Deck", "Task List", "BOM", and "Google Drive" will become input text boxes at the bottom of this section with the labels being "Slide Deck", "Task List", "BOM", and "Google Drive". 
- [x] The "status" field on the top right corner of this section should be a dropdown list with the following three selections: "Inactive", "Active", "Complete".
- [x] The "$" unit for the "Budget" field should be a read-only field placed on the left side of the input box. The user will only be changing the numbers. See mocks for clarification. 

### Summary
- [x] The entire section will become an HTML textarea where the users are able to edit the details in the summary section.

### Goals
- [x] Each existing list item will become a text box with a delete button for each line item located on the right hand side of the screen.
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Features
- [x] Each existing list item will become a text box with a delete button for each line item located on the right hand side of the screen.
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Other Constraints 
- [x] Each existing list item will become a text box with a delete button for each line item located on the right hand side of the screen.
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Rules
- [x] Each existing rule will become a text box with a delete button on the upper left hand corner of each text box.
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Changes
- [x] View only section. The section should not be editable. It should still be a part of the form, but should remain a view-only section.

### Work Packages
- [x] Existing work packages should not be editable.

### General 
- [x] There should be a sticky footer with two buttons: "Cancel" and "Save". The footer will be slightly transparent.
