### ISSUE TITLE
Projects - Work Package Edit Form

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#362]
## Description

A new component needs to be created so that project managers can edit a work package. This component will be a form that will look similar to the work package details page, except that all the fields within within the work package will be editable text boxes rather than view-only details about the work package. 

## Background
The idea is that when project managers click on the "edit" button (which will be completed in another ticket), this form will be populated with the current information of the work package, so that project managers can directly edit and save the details. This ticket is to make the form that the project managers will see when they click the "edit" button. Do not worry about populating the text boxes with the current values, as that will be completed in another ticket. The focus of this ticket is to only create the front-end visual.

## Proposed Solution
\*\***For all sections listed below, the headers for each section (Work Package Details, Dependencies, etc.) should not be editable**\*\*

### Work Package Details 
- [x] The labels for each field will remain exactly the same and in the same location. Only the details portion for each field will change and will become input text boxes. 
- [x] The "Start Date" field should become a date picker.
- [x] The "End Date" field should be read only, since it is calculated by the start date and duration.
- [x] The percent symbol for the "Progress" and "Expected Progress" fields should be a read-only field. The user will only be changing the numbers. See mocks for clarification.
- [x] The "weeks" unit for the "Duration" field should be a read-only field. The user will only be changing the numbers. See mocks for clarification.
- [x] The "status" field on the top right corner of this section should be a dropdown list with the following three selections: "Inactive", "Active", "Complete".

### Dependencies
- [x] Each existing dependency will become a text box with a delete button on the upper left hand corner of each text box. 
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Expected Activities
- [x] Each existing expected activity will become a text box with a delete button for each line item located on the right hand side of the screen.
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Deliverables
- [x] Each existing deliverable will become a text box with a delete button for each line item located on the right hand side of the screen.
- [x] At the end of the list, there should be a blank text box with an add button on the right hand side of the text box. This text box and button should always be present, whether or not there are any list items present.

### Changes
- [x] View only section. The section should not be editable. It should still be a part of the form, but should remain a view-only section.

### General 
- [x] There should be a sticky footer with two buttons: "Cancel" and "Save". The footer will be slightly transparent.

## Mocks
https://www.figma.com/file/qmXuySSwfiD942HwmSSEMe/NERPM-Desktop?node-id=392%3A225
