### ISSUE TITLE
Projects - Work Package Form Validation

### ISSUE THREAD

**Issue by KincentLan** [Northeastern-Electric-Racing/PM-Dashboard-v2#369]
## Description
When implementing change requests, project managers will edit a form populated with the information from a work package. We need to implement front-end validation to ensure that the user inputs and submits proper data. Having front-end validation helps ensure that the information is correctly formatted.

## Background
The application does not currently support any front-end validation. Including this in the work package edit form will help ensure that the submitted data is consistent with the formatting in our database. Validation will be similar to the ones in #370.

### Work Package Details
- [x] The "Duration" and "Progress" fields should contain only numbers
- [x] WBS # and "Expected Progress" fields: none because it is read-only

### Dependencies
- [x] All elements pass the `validateWBS()` function provided by the `utils` package

### Expected Activities
- [x] Ensure that the section is not empty

### Deliverables
- [x] Ensure that the section is not empty

### Changes
- [x] No form validation needed because this section should be read-only

**Comment by z-roth** [comment]
There should be no validation for the WBS # field, as it is a read-only field on the form.

**Comment by jamescd18** [comment]
Updated spec to fix errors
