### ISSUE TITLE
Projects - Project Form Validation

### ISSUE THREAD

**Issue by KincentLan** [Northeastern-Electric-Racing/PM-Dashboard-v2#370]
## Description
When implementing change requests, project managers will edit a form populated with the information from a project. We need to implement front-end validation to ensure that the user inputs and submits proper data. Having front-end validation helps ensure that the information is correctly formatted.

## Background
The application does not currently support any front-end validation. Including this in the project edit form will help ensure that the submitted data is consistent with the formatting in our database. Validation will be similar to the ones in #369.

### Project Details
- [ ] The "Slide Deck", "Task List", "BOM", and "Google Drive" fields have no validation
- [ ] The "Budget" field contains only integers, >= 0
- [ ] WBS # field is read-only

### Summary
- [ ] Ensure that the section is not empty

### Goals
- [ ] Ensure no bullets are empty strings

### Features
- [ ] Ensure no bullets are empty strings

### Other Constraints 
- [ ] Ensure no bullets are empty strings

### Rules
- [ ] Ensure no bullets are empty strings

### Changes
- [ ] No form validation needed because this section should be read-only

### Work Packages
- [ ] No form validation needed because this section should be read-only
