### ISSUE TITLE
General - Launch Application MVP

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#385]
## Description:
NEEDS EDITING FOR SOFT, MEDIUM, AND ACTUAL LAUNCH

Our users need to be able to use the application, and that requires launching the application for the very first time. This will be the MVP (Minimum Viable Product) launch and only include the smallest set of features for a usable application. For this to happen, we need to prepare our production environment to users to start using.

## Prerequisites:
- [x] #381
- [x] #204
- [x] #398 

## Tickets:

- [ ] General - Prepare Production Data
- [ ] General - Load Production Data
- [ ] General - Final Production Checks
