### ISSUE TITLE
Change Requests - Update Change Requests to Fit Customer Needs

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#435]
## Prerequisites
- [x] #419 

## Description

Basically the database has the latest naming for the different types of Change Requests, but the front-end / application types are out of date. Also, we need to make some small modifications to change requests to satisfy customer requirements for MVP launch.

Once the app types enums match the database types enums, then we should be able to remove the converter function and usage from the change requests endpoint. This should work since the backend should just be able to grab the string from the db, stringify it for sending over HTTP, front-end picks it up and `JSON.parse()`, converting it to the app types enum which has the same underlying all caps snake case strings. This will allow us to simplify the back-end.

## Tasks
- [x] rename front-end types to match database
- [x] update test stub data
- [x] ensure enums are working properly in entire app
- [x] remove enum convert from back-end
- [x] Rename `DEFINIITION_CHANGE` to `REDEFINITION`
- [ ] Add `documentationLink` to the Scope Change Request as a `string`
- [ ] Add `DESIGN` as an item in the `Scope_CR_Why_Type` enum

**Comment by jamescd18** [comment]
Discussion with Head of Project Management, Der Chi Lin:

- [ ] Rename `DEFINIITION_CHANGE` to `REDEFINITION`
- [ ] Add `documentationLink` to the Scope Change Request as a `string`
- [ ] Add `DESIGN` as an item in the `Scope_CR_Why_Type` enum
