### ISSUE TITLE
General - Enhance Displayed Values

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#474]
## Description

There's various aspects of the displayed values for project and work packages and change requests that are not so desirable. Some aspects involve standardizing the way something is displayed, others involve simply pushing the business logic into the back-end so that the front-end can focus on just displaying values.

## Tickets

- [ ] Projects - Correct and Move Duration Calculation to Back-End
- [ ] Projects - Move End Date Calculation to Back-End
- [ ] General - Standardize Date Time Display
- [ ] Projects - Add Expected Progress Calculation
- [ ] Projects - Add Timeline Status Calculation
- [ ] Change Requests - Display CR Review Date
- [ ] #473
