### ISSUE TITLE
Projects - Form Validation for Create New Work Package Form 

### ISSUE THREAD

**Issue by kevinyu328** [Northeastern-Electric-Racing/PM-Dashboard-v2#496]
## Description

When creating a new work package, project managers will have to fill out the new work package form. We need to implement front-end validation to ensure that the user inputs and submits proper data. Having front-end validation helps ensure that the information put into the new work package form is correctly formatted.

## Background

Including this in the new work package form will help ensure that the submitted data in the form is consistent with the formatting in the database. This is mainly for project managers who need to create new work packages when implementing a change request. 

### Work Package Details
- [x] Work Package Form field should contain text
- [x] "Project W.B.S # " - element passes the `isProject()` function provided by the `utils` package
- [x] Start Date field should be a real date
- [x] Duration field should contain only a number

### Dependencies
- [x] All elements pass the `validateWBS()` function provided by the `utils` package

### Expected Activites
- [x] No validation needed 

### Deliverables
- [x] No validation needed
