### ISSUE TITLE
General - Disable certain actions for guest users

### ISSUE THREAD

**Issue by jamescd18** [Northeastern-Electric-Racing/PM-Dashboard-v2#613]
## Overview

For MVP launch, we want a quick and simple way to prevent Guest users from making creation or editing changes to the data in the application. This will prevent the possibility of data being changed by unaware or malicious users, and avoid the headache of needing to revert said changed data.

## Tasks
- [x] make navigation buttons disabled in front-end
  - [x] accept / deny change requests
  - [x] create new project / work package
  - [x] edit project / work package
- [x] make form submission buttons disabled in front-end
  - [x] accept / deny change requests
  - [x] create new project / work package
- [x] make create / edit endpoints return forbidden
  - [x] review change requests
  - [x] create project / work package
  - [x] edit project / work package
- [x] show role on settings page
